# Introduction to Python: Dataframes

Nearly all researchers work with tabular data at one time or another. In this lesson, we will practice with **dataframes**, a Python data structure designed to work with tabular data, using the **Pandas library**. We will create our own dataframes, read in data from .csv files to a dataframe, subset and combine dataframes, and add or modify columns (variables) and observations (rows). We will also examine how these tasks work with messy and large datasets (i.e. millions or rows).

To learn more about Pandas, visit the webpage for the [Pandas library](https://pandas.pydata.org/).

For further practice with Python and Pandas dataframes, visit:

1. Software Carpentries [Pandas DataFrames](http://swcarpentry.github.io/python-novice-gapminder/08-data-frames/index.html) lesson.
2. The **Pandas basics** and **intermediate** [tutorials offered by Constellate](https://github.com/ithaka/constellate-notebooks/tree/master).
3. Chapter 3, ["Data Analysis (Pandas)"](https://melaniewalsh.github.io/Intro-Cultural-Analytics/03-Data-Analysis/01-Pandas-Basics-Part1.html) in Melanie Walsh's *Introduction to Cultural Analytics & Python*.

Note: All three platforms above offer excellent lessons for learning how to perform various other tasks in Python. Check them out.

Finally, don't worry about memorizing all the functions and syntax needed to work with Pandas. You can use the [Python Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) as a handy guide to remind you of some of these key functions.


<h2 style="text-align:center;font-size:300%;">Dataframes: The Basics<h1> 
  <img src="https://media.geeksforgeeks.org/wp-content/cdn-uploads/creating_dataframe1.png" style="width:%40;">

A dataframe is a particular data structure that includes:
+ **rows** that record each observation of data
+ **columns** that record different attributes / measures / variables for each observation
+ **column labels** that describe the data recorded in each column
+ **index labels** that differentiate between each observations

## I. Create a dataframe

1. First, we need to import the [**Pandas**, Python's data analysis library](https://pandas.pydata.org/) that allows us to work with dataframes. It is almost universal practice among Python users to import Pandas under the name "pd" to serve as a useful abbreviation we can use when calling Pandas functions. We will also import **pathlib** and **glob** to help us work with file paths.

In [221]:
import pandas as pd
import pathlib, glob
from pathlib import Path

2. There are many ways to create a dataframe:
    +  Perhaps the most common way is to **load an existing dataset saved as a *.csv*** (Comma Separated Values) file and read it in directly as a Pandas dataframe. We will introduce that method in the next section.
    +  **Import data from other files and convert it into a dataframe.** For example, you could write a Python script iterating over 1000s of text files and create a Pandas dataframe with basic information about each text (i.e. file names, number of words, etc.)
    + **We can also create a dataframe from scratch** (usually only used to demo or practice with dataframes):

In [222]:
# this example comes from Constellate's Pandas 1 tutorial
  ## https://lab.constellate.org/ilr-review-primary/notebooks/tdm-notebooks-2023-04-19T13%3A37%3A13.281Z/pandas-1.ipynb
wcup = pd.DataFrame({"Year": [2022, 
                              2018, 
                              2014, 
                              2010, 
                              2006, 
                              2002, 
                              1998, 
                              1994, 
                              1990,
                              1986], 
                     "Champion": ["Argentina", 
                                  "France", 
                                  "Germany", 
                                  "Spain", 
                                  "Italy", 
                                  "Brazil", 
                                  "France", 
                                  "Brazil", 
                                  "Germany", 
                                  "Argentina"], 
                     "Host": ["Qatar", 
                              "Russia", 
                              "Brazil", 
                              "South Africa", 
                              "Germany", 
                              "Korea/Japan", 
                              "France", 
                              "USA", 
                              "Italy", 
                              "Mexico"]
                    })

3. In the above example, we are directly inputting a dataframe using the Python **dictionary** data structure. For more on Python dictionaries (click here)[https://www.w3schools.com/python/python_dictionaries.asp]. 

*This is beyond the scope of this lesson, but if you are curious, you can learn more about Python dictionaries from [w3schools](https://www.w3schools.com/python/python_dictionaries.asp) or [GeeksforGeeks](https://www.geeksforgeeks.org/python-dictionary/)*

Let's view what the resulting dataframe looks like by typing the variable name we used to save our World Cup dataframe into memory:

In [223]:
wcup

   Year   Champion          Host
0  2022  Argentina         Qatar
1  2018     France        Russia
2  2014    Germany        Brazil
3  2010      Spain  South Africa
4  2006      Italy       Germany
5  2002     Brazil   Korea/Japan
6  1998     France        France
7  1994     Brazil           USA
8  1990    Germany         Italy
9  1986  Argentina        Mexico

We will come back to this dataset below.

## II. Read a Dataframe

Besides the basic Men's World Cup dataset created above, in this lesson we will also be working with:
 
+ the famous Gapminder dataset charting changing life expectancies and GDP values for countries over time. (used by Software Carpentries)
<!--+ The Bellevue Almshouse dataset (used in [Walsh, *Intro to Cultural Analytics*](https://melaniewalsh.github.io/Intro-Cultural-Analytics/03-Data-Analysis/01-Pandas-Basics-Part1.html) and created by Anelise Hanson Shrout. Original [link to data here](https://docs.google.com/spreadsheets/d/1uf8uaqicknrn0a6STWrVfVMScQQMtzYf5I_QyhB9r7I/edit#gid=2057113261). An [essay about this dataset is here](https://crdh.rrchnm.org/essays/v01-10-(re)-humanizing-data/).)-->
+ Hollywood Film Dialogue dataset (also used in Walsh. Original data from Hannah Anderson and Matt Daniels, ["Film Dialogue from 2,000 screenplays, Broken down by Gender and Age."](https://pudding.cool/2017/03/film-dialogue/))

4. To read data in, we will use the Pandas [**read_csv** function](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html). First, however, we need to create a path to the folder where our datasets are saved. We will use the **Path** function from the **pathlib** library.

In [224]:
Path.cwd()

WindowsPath('c:/Users/F0040RP/Documents/DartLib_RDS/python_workshops/py-essentials_ws/lessons/02_dataframes/code')

In [225]:
gapminder_df = pd.read_csv("../../../data/gapminder.csv")
movie_df = pd.read_csv("../../../data/movie_data.csv")

We can print out the first 5 rows of this dataframe using the **.head()** method. *Methods* are functions which are applied only to specified data types. I.e. "string methods" are those functions that only work on text strings.

In [226]:
gapminder_df.head()

       country continent  year  lifeExp       pop  gdpPercap
0  Afghanistan      Asia  1952    28.80   8425333     779.45
1  Afghanistan      Asia  1957    30.33   9240934     820.85
2  Afghanistan      Asia  1962    32.00  10267083     853.10
3  Afghanistan      Asia  1967    34.02  11537966     836.20
4  Afghanistan      Asia  1972    36.09  13079460     739.98

Here is a quick summary of what you see above from Melanie Walsh's online book, [*Introduction to Cultural Analytics & Python*](https://melaniewalsh.github.io/Intro-Cultural-Analytics/03-Data-Analysis/01-Pandas-Basics-Part1.html):

There are a few important things to note about the DataFrame displayed here:

+ Index
    - The bolded ascending numbers in the very left-hand column of the DataFrame is called the Pandas Index. You can select rows based on the Index.
    - By default, the Index is a sequence of numbers starting with zero. However, you can change the Index to something else, such as one of the columns in your dataset.

+ Truncation
    - The DataFrame is truncated, signaled by the ellipses in the middle ... of every column.
    - The DataFrame is truncated because we set our default display settings to 100 rows. Anything more than 100 rows will be truncated. To display all the rows, we would need to alter Pandas’ default display settings yet again.

+ Rows x Columns
    - Pandas reports how many rows and columns are in this dataset at the bottom of the output (n rows x n columns).
    - This is very useful!

*In addition, I would also add that in the preview of the dataframe above - at least as viewed within JHub - you can click on a pen/highlighter icon to view the whole dataframe.*

## III. Get summary data to learn more about a dataframe

6. Now, often the first thing we want to do with a new dataset is to explore the size of the dataset and the type and range of data it contains. Pandas dataframes come with a variety of built-in methods designed to explore dataframes. These include:
   
   ```
   # syntax: dateframe_name.method()

   .head()
   .tail()
   .shape
   .info()
   .sample()
   .describe()
   .columns()
   .value_counts()
   ```
   
7. Run the following functions and then use hashtags ```#``` to add in comments about what each does.

In [227]:
movie_df.head(12)  #

,Title,duration_minutes,MPA,Rating,votes,meta_score,genres,parent_genres,date,year,...,budget_estimated,budget_value,budget_currency,grossww_value,grossww_currency,directors,stars,awards_content,Languages,description
0,Toy Story 3,103,G,8.30,926000,92.00,"['Computer Animation', 'Supernatural Fantasy',...","animation, fantasy, act-ad, comedy, family",2010-06-18,2010.00,...,True,200000000,$,1067316101,$,['Lee Unkrich'],"['Tom Hanks', 'Tim Allen', 'Joan Cusack', 'Ned...","Won 2 Oscars, 63 wins & 96 nominations total","['English', 'Spanish']",The toys are mistakenly delivered to a day-car...
1,Alice in Wonderland,108,PG,6.40,453000,53.00,"['Dark Fantasy', 'Fairy Tale', 'Adventure', 'F...","fantasy, act-ad, family, mystery",2010-03-05,2010.00,...,True,200000000,$,1025468216,$,['Tim Burton'],"['Mia Wasikowska', 'Johnny Depp', 'Helena Bonh...","Won 2 Oscars, 35 wins & 65 nominations total",['English'],Nineteen-year-old Alice returns to the magical...
2,Iron Man 2,124,PG-13,6.90,898000,57.00,"['Sci-Fi Epic', 'Superhero', 'Action', 'Sci-Fi']","scifi, act-ad",2010-05-07,2010.00,...,True,200000000,$,623933331,$,['Jon Favreau'],"['Robert Downey Jr.', 'Mickey Rourke', 'Gwynet...","Nominated for 1 Oscar, 7 wins & 45 nominations...","['English', 'French', 'Russian']",With the world now aware of his identity as Ir...
3,The Twilight Saga: Eclipse,124,PG-13,5.10,269000,58.00,"['Supernatural Fantasy', 'Teen Fantasy', 'Teen...","fantasy, romance, act-ad, drama, mystery, thri...",2010-06-30,2010.00,...,True,68000000,$,698513085,$,['David Slade'],"['Kristen Stewart', 'Robert Pattinson', 'Taylo...","Awards, 23 wins & 35 nominations total",['English'],As a string of mysterious killings grips Seatt...
4,Harry Potter and the Deathly Hallows: Part 1,146,PG-13,7.70,627000,65.00,"['Dark Fantasy', 'Supernatural Fantasy', 'Swor...","fantasy, act-ad, family, mystery",2010-11-19,2010.00,...,True,125000000,$,974919063,$,['David Yates'],"['Daniel Radcliffe', 'Emma Watson', 'Rupert Gr...","Nominated for 2 Oscars, 15 wins & 55 nominatio...","['English', 'Latin']",Harry Potter is tasked with the dangerous and ...
5,Inception,148,PG-13,8.80,2700000,74.00,"['Action Epic', 'Adventure Epic', 'Epic', 'Psy...","act-ad, thriller, scifi",2010-07-16,2010.00,...,True,160000000,$,839030630,$,['Christopher Nolan'],"['Leonardo DiCaprio', 'Joseph Gordon-Levitt', ...","Won 4 Oscars, 159 wins & 220 nominations total","['English', 'Japanese', 'French']",A thief who steals corporate secrets through t...
6,Despicable Me,95,PG,7.60,607000,72.00,"['Computer Animation', 'Slapstick', 'Urban Adv...","animation, comedy, act-ad, mystery, family, scifi",2010-07-09,2010.00,...,True,69000000,$,544174973,$,"['Pierre Coffin', 'Chris Renaud']","['Steve Carell', 'Jason Segel', 'Russell Brand...","Nominated for 1 BAFTA Award, 3 wins & 41 nomin...",['English'],"Gru, a criminal mastermind, adopts three orpha..."
7,Shrek Forever After,93,PG,6.30,234000,58.00,"['Computer Animation', 'Fairy Tale', 'Parody',...","animation, fantasy, comedy, act-ad, family, ro...",2010-05-21,2010.00,...,True,165000000,$,752600867,$,['Mike Mitchell'],"['Mike Myers', 'Cameron Diaz', 'Eddie Murphy',...","Awards, 1 win & 13 nominations total",['English'],Rumpelstiltskin tricks a mid-life crisis burde...
8,How to Train Your Dragon,98,PG,8.10,837000,75.00,"['Computer Animation', 'Sword & Sorcery', 'Tee...","animation, fantasy, act-ad, family",2010-03-26,2010.00,...,True,165000000,$,494879860,$,"['Dean DeBlois', 'Chris Sanders']","['Jay Baruchel', 'Gerard Butler', 'Christopher...","Nominated for 2 Oscars, 25 wins & 63 nominatio...",['English'],A hapless young Viking who aspires to hunt dra...
9,Tangled,100,PG,7.70,517000,71.00,"['Computer Animation', 'Fairy Tale', 'Feel-Goo...","animation, fantasy, romance, musical, act-ad, ...",2010-11-24,2010.00,...,True,260000000,$,591806017,$,"['Nathan Greno', 'Byron Howard']","['Mandy Moore', 'Zachary Levi', 'Donna Murphy'...","Nominated for 1 Oscar, 10 wins & 42 nomination...","['English', 'German']",The magically long-haired Rapunzel has spent h...
10,The Karate Kid,140,PG,6.20,215000,61.00,"['Action', 'Drama', 'Family', 'Sport']","act-ad, drama, family, sports",2010-06-11,2010.00,...,True,40000000,$,359126022,$,['Harald Zwart'],"['Jackie Chan', 'Jaden Smith', 'Taraji P. Hens...","Awards, 5 wins & 12 nominations total","['English', 'Mandarin']",Work causes a single mother to move to China w...
11,Tron: Legacy,125,PG,6.80,364000,49.00,"['Artificial Intelligence', 'Cyberpunk', 'Acti...","scifi, act-ad",2010-12-17,2010.00,...,True,170000000,$,409912892,$,['Joseph Kosinski'],"['Jeff Bridges', 'Garrett Hedlund', 'Olivia Wi...","Nominated for 1 Oscar, 10 wins & 52 nomination...",['English'],The son of a virtual world designer goes looki...

In [228]:
movie_df.tail() #

,Title,duration_minutes,MPA,Rating,votes,meta_score,genres,parent_genres,date,year,...,budget_estimated,budget_value,budget_currency,grossww_value,grossww_currency,directors,stars,awards_content,Languages,description
2964,Opus,104,R,5.90,1900,42.00,"['Psychological Drama', 'Drama']",drama,2025-03-14,2025.00,...,True,10000000,$,1922230,$,['Mark Anthony Green'],"['Ayo Edebiri', 'John Malkovich', 'Juliette Le...",NaN,['English'],A writer travels to the compound of a pop icon...
2965,Putin,109,R,3.10,1400,NaN,"['Biography', 'Crime', 'Drama', 'Thriller', 'W...","drama, mystery, thriller, act-ad",2025-01-10,2025.00,...,True,15000000,$,406786,$,['Patryk Vega'],"['Tomasz Dedek', 'Justyna Karlowska', 'Thomas ...",NaN,['English'],"A portrait of a formidable political figure, u..."
2966,Borderline,94,R,5.30,2000,63.00,"['Dark Comedy', 'Psychological Horror', 'Psych...","comedy, horror, thriller",2025-03-14,2025.00,...,True,5000000,$,13472,$,['Jimmy Warden'],"['Samara Weaving', 'Ray Nicholson', 'Eric Dane...",NaN,['English'],A bodyguard protects a pop superstar and her a...
2967,Alarum,95,R,3.30,2200,23.00,"['Action', 'Crime', 'Thriller']","act-ad, mystery, thriller",2025-01-16,2025.00,...,True,20000000,$,189036,$,['Michael Polish'],"['Scott Eastwood', 'Sylvester Stallone', 'Will...",NaN,['English'],"Two rogue spies go off-grid, marry, and come u..."
2968,Into the Deep,90,R,3.40,784,NaN,"['B-Action', 'Action', 'Thriller']","act-ad, thriller",2025-01-24,2025.00,...,True,3000000,$,87338,$,['Christian Sesma'],"['Callum McGowan', 'Scout Taylor-Compton', 'Jo...",NaN,['English'],Modern day pirates on the hunt for sunken drug...

In [229]:
movie_df.shape #

(2969, 24)

In [230]:
movie_df.info() #

<class 'pandas.DataFrame'>
RangeIndex: 2969 entries, 0 to 2968
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             2969 non-null   str
 1   duration_minutes  2969 non-null   int64
 2   MPA               2860 non-null   str
 3   Rating            2969 non-null   float64
 4   votes             2969 non-null   int64
 5   meta_score        2637 non-null   float64
 6   genres            2969 non-null   str
 7   parent_genres     2969 non-null   str
 8   date              2968 non-null   str
 9   year              2968 non-null   float64
 10  month             2968 non-null   float64
 11  day               2968 non-null   float64
 12  daynum            2968 non-null   float64
 13  date_partial      2969 non-null   bool
 14  budget_estimated  2969 non-null   bool
 15  budget_value      2969 non-null   int64
 16  budget_currency   2969 non-null   str
 17  grossww_value     2969 non-null   int64
 18  grossww_currency  2969 non-null   str
 19  directors         2969 non-null   str
 20  stars             2960 non-null   str
 21  awards_content    2542 non-null   str
 22  Languages         2969 non-null   str
 23  description       2967 non-null   str
dtypes: bool(2), float64(6), int64(4), str(12)
memory usage: 516.2 KB

In [231]:
movie_df.sample(10) #

,Title,duration_minutes,MPA,Rating,votes,meta_score,genres,parent_genres,date,year,...,budget_estimated,budget_value,budget_currency,grossww_value,grossww_currency,directors,stars,awards_content,Languages,description
2565,The Power of the Dog,126,R,6.80,200000,89.00,"['Period Drama', 'Psychological Drama', 'Drama...","drama, western",2021-12-01,2021.00,...,True,35000000,$,271009,$,['Jane Campion'],"['Benedict Cumberbatch', 'Kirsten Dunst', 'Jes...","Won 1 Oscar, 287 wins & 324 nominations total","['English', 'Shoshoni', 'Italian', 'French']",Charismatic rancher Phil Burbank inspires fear...
1590,Alice Through the Looking Glass,113,PG,6.20,128000,34.00,"['Fairy Tale', 'Quest', 'Adventure', 'Family',...","fantasy, act-ad, family, mystery",2016-05-27,2016.00,...,True,170000000,$,299820798,$,['James Bobin'],"['Mia Wasikowska', 'Johnny Depp', 'Helena Bonh...","Awards, 4 wins & 20 nominations total",['English'],Alice is appointed to save her beloved Mad Hat...
1949,A Ghost Story,92,R,6.80,84000,84.00,"['Drama', 'Fantasy', 'Mystery', 'Romance']","drama, fantasy, mystery, romance",2017-07-28,2017.00,...,True,100000,$,1951683,$,['David Lowery'],"['Casey Affleck', 'Rooney Mara', 'McColm Cepha...","Awards, 11 wins & 21 nominations total","['English', 'Spanish']","In this singular exploration of legacy, love, ..."
1476,Embrace of the Serpent,125,Not Rated,7.80,25000,82.00,"['Jungle Adventure', 'Adventure', 'Biography',...","act-ad, drama",2015-05-25,2015.00,...,True,1400000,$,3217212,$,['Ciro Guerra'],"['Nilbio Torres', 'Jan Bijvoet', 'Antonio Bolí...","Nominated for 1 Oscar, 46 wins & 32 nomination...","['Spanish', 'Portuguese', 'Aboriginal', 'Germa...",The story of the relationship between Karamaka...
1444,Our Brand Is Crisis,107,R,6.10,24000,53.00,"['Political Drama', 'Comedy', 'Drama']","drama, comedy",2015-10-30,2015.00,...,True,28000000,$,9002261,$,['David Gordon Green'],"['Sandra Bullock', 'Billy Bob Thornton', 'Anth...","Awards, 2 nominations total","['English', 'Spanish']",A battle-hardened American political consultan...
2417,Trolls World Tour,91,PG,6.10,31000,51.00,"['Computer Animation', 'Jukebox Musical', 'Adv...","animation, musical, act-ad, comedy, family, fa...",2020-04-10,2020.00,...,True,90000000,$,49276818,$,"['Walt Dohrn', 'David P. Smith']","['Anna Kendrick', 'Justin Timberlake', 'Rachel...","Awards, 4 wins & 22 nominations total",['English'],When the Queen of the Hard Rock Trolls tries t...
2350,Hollywould,90,NaN,3.70,144,NaN,"['Crime', 'Mystery', 'Thriller']","mystery, thriller",2019-11-15,2019.00,...,True,250000,$,11888,$,['Joshua Coates'],"['Eric Roberts', 'Torrei Hart', 'Danny Plaza',...",NaN,['English'],"Award winning writer, celebrity Mark Travis se..."
1745,The Hollars,88,PG-13,6.60,15000,53.00,"['Comedy', 'Drama', 'Romance']","comedy, drama, romance",2016-08-26,2016.00,...,True,3800000,$,1138609,$,['John Krasinski'],"['Sharlto Copley', 'Charlie Day', 'Richard Jen...","Awards, 2 wins & 5 nominations total",['English'],A man returns to his small hometown after lear...
140,Please Give,87,R,6.60,12000,78.00,"['Comedy', 'Drama']","comedy, drama",2010-06-18,2010.00,...,True,3000000,$,4313829,$,['Nicole Holofcener'],"['Catherine Keener', 'Oliver Platt', 'Rebecca ...","Awards, 5 wins & 18 nominations total",['English'],"In New York City, a husband and wife butt head..."
1663,Middle School: The Worst Years of My Life,92,PG,6.10,10000,51.00,"['Comedy', 'Family']","comedy, family",2016-10-07,2016.00,...,True,8500000,$,23316139,$,['Steve Carr'],"['Griffin Gluck', 'Lauren Graham', 'Alexa Nise...","Awards, 5 nominations total","['English', 'Central Khmer', 'Spanish']",After his new principal Dwight destroys his sk...

In [232]:
movie_df.describe() #

,duration_minutes,Rating,votes,meta_score,year,month,day,daynum,budget_value,grossww_value
count,2969.00,2969.00,2969.00,2637.00,2968.00,2968.00,2968.00,2968.00,2969.00,2969.00
mean,108.26,6.29,121682.40,54.93,2015.98,6.61,16.07,186.10,38670601.68,117300501.53
std,18.46,1.04,199245.60,17.24,4.13,3.47,8.54,106.06,53862406.06,234361450.31
min,0.00,1.30,8.00,1.00,2010.00,1.00,1.00,1.00,1.00,601.00
25%,95.00,5.70,10000.00,42.00,2013.00,4.00,9.00,92.00,5000000.00,2001176.00
50%,105.00,6.40,50000.00,55.00,2015.00,7.00,16.00,191.00,18000000.00,29048571.00
75%,118.00,7.00,145000.00,67.00,2019.00,10.00,23.00,278.00,45000000.00,116471580.00
max,216.00,9.20,2700000.00,100.00,2025.00,12.00,31.00,364.00,414900000.00,2799439100.00

In [233]:
movie_df.columns

Index(['Title', 'duration_minutes', 'MPA', 'Rating', 'votes', 'meta_score',
       'genres', 'parent_genres', 'date', 'year', 'month', 'day', 'daynum',
       'date_partial', 'budget_estimated', 'budget_value', 'budget_currency',
       'grossww_value', 'grossww_currency', 'directors', 'stars',
       'awards_content', 'Languages', 'description'],
      dtype='str')

In [234]:
## We can also get summary information about individual columns. For example:
pd.options.display.float_format = '{:.2f}'.format
movie_df['budget_value'].describe()

count        2969.00
mean     38670601.68
std      53862406.06
min             1.00
25%       5000000.00
50%      18000000.00
75%      45000000.00
max     414900000.00
Name: budget_value, dtype: float64

Let's see what happens when we apply **.describe()** to a column filled with categorical data:

In [235]:
movie_df['parent_genres'].describe()

count      2969
unique      852
top       drama
freq        175
Name: parent_genres, dtype: object

In [236]:
## or:
movie_df['parent_genres'].value_counts()

parent_genres
drama                                        175
comedy, drama                                 92
documentary                                   84
comedy                                        79
comedy, drama, romance                        74
                                            ...
act-ad, comedy, scifi, fantasy                 1
scifi, comedy, thriller                        1
animation, fantasy, sports, act-ad, drama      1
fantasy, drama, act-ad                         1
drama, mystery, thriller, act-ad               1
Name: count, Length: 852, dtype: int64

<div class="alert alert-info" role="alert"><h3 style="color:blue;">Exercises for Parts II and III</h3>

<p style="color:blue;">7. Take a look at the [Python Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf). Are there any other summary data you would like to retrieve from this dataset. Try it below:</p></div>

<div class="alert alert-info" role="alert"><p style="color:blue;">8. Now let's open the Film Dialogue dataset. Copy and paste the code from Part II, Numbers 4 and 5 below and then modify that code to open the film dialogue dataset. (Navigate to the film-dialogue folder using the folder directory on the left. You will need to identify the specific file path to and file name of the film dataframe).</p>
</div>

In [237]:
film_path = Path("~/shared/RR-workshop-data/film-dialogue").expanduser() 
film_dialogue_df = pd.read_csv(Path(film_path, "Pudding-Film-Dialogue-Clean.csv"))
film_dialogue_df.head()

,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,script_id
0,The Bridges of Madison County,1995,Betty,woman,311,0.05,35.00,142.00,280
1,The Bridges of Madison County,1995,Carolyn Johnson,woman,873,0.14,NaN,142.00,280
2,The Bridges of Madison County,1995,Eleanor,woman,138,0.02,NaN,142.00,280
3,The Bridges of Madison County,1995,Francesca Johns,woman,2251,0.35,46.00,142.00,280
4,The Bridges of Madison County,1995,Madge,woman,190,0.03,46.00,142.00,280

\*\***A note about data entry and humans (and things like gender, race, class, etc.)**: When people collect data, they often have to reduce complex phenomena to individual categories. This is problematic when performed on objects that do not neatly fit into pre-existing categories (or any categories for that matter). This is especially problematic when assigned to humans. How do you reduce humans to a racial or ethnic category when those categories are, to at least some extent, social inventions? When a person comes from a mixed background? How do you reduce people to two gender categories, when many people do not feel they are adequately represented by such categories? Keep this in mind when reviewing datasets that place people into hard and fast categories (as the above dataset does for the gender of movie characters).

<div class="alert alert-info" role="alert"><p style="color:blue;">9. Using some of the methods introduced in Part III and the [Python Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf), answer the following questions:</p>
<ul>
    <li style="color:blue;">How many rows and columns are there in this dataset?</li>
</ul>
</div>

In [238]:
film_dialogue_df.shape

(23047, 9)

<div class="alert alert-info" role="alert">
<ul>
    <li style="color:blue;">What are the range of dates for the films included in this dataset?</li>
</ul>
</div>

In [239]:
film_dialogue_df.describe()

,release_year,words,proportion_of_dialogue,age,gross,script_id
count,23047.00,23047.00,23047.00,18262.00,19386.00,23047.00
mean,1998.13,907.90,0.09,42.28,106.74,4194.80
std,14.75,1399.62,0.11,57.91,145.86,2473.04
min,1929.00,101.00,0.00,3.00,0.00,280.00
25%,1992.00,193.00,0.02,30.00,22.00,2095.00
50%,2001.00,396.00,0.04,39.00,56.00,3694.00
75%,2009.00,980.00,0.10,50.00,136.00,6224.50
max,2015.00,28102.00,0.92,2009.00,1798.00,9254.00

<div class="alert alert-info" role="alert">
<ul>
    <li style="color:blue;">How many men vs. women (** - see note above) are included in this dataset</li>
</ul>
</div>

In [240]:
film_dialogue_df['gender'].value_counts()

gender
man      16131
woman     6911
?            5
Name: count, dtype: int64

<div class="alert alert-info" role="alert">
<ul>
    <li style="color:blue;">What is the average age of film characters in this dataset?</li>

</ul>
</div>

In [241]:
film_dialogue_df['age'].describe()

count   18262.00
mean       42.28
std        57.91
min         3.00
25%        30.00
50%        39.00
75%        50.00
max      2009.00
Name: age, dtype: float64

## IV. Access Parts of a Data Frame

<div class="alert alert-success" role="alert"><p style="color:green">10. Let's take a look at our World Cup data again. Use the **.head()** method to output the first 5 rows of this dataset (wcup).</p></div>

In [242]:
wcup.head()

   Year   Champion          Host
0  2022  Argentina         Qatar
1  2018     France        Russia
2  2014    Germany        Brazil
3  2010      Spain  South Africa
4  2006      Italy       Germany

11. We can use the **.iloc[..., ...]** method to extract particular columns, rows, or cells. For example to retrieve the first row or first column, we would do the following:

In [243]:
wcup.iloc[0]

Year             2022
Champion    Argentina
Host            Qatar
Name: 0, dtype: object

In [244]:
wcup.iloc[:,0]

0    2022
1    2018
2    2014
3    2010
4    2006
5    2002
6    1998
7    1994
8    1990
9    1986
Name: Year, dtype: int64

<div class="alert alert-success" role="alert"><p style="color:green">11b. Can you guess how to extract only the last column?</p></div>

In [245]:
wcup.iloc[:,-1]

0           Qatar
1          Russia
2          Brazil
3    South Africa
4         Germany
5     Korea/Japan
6          France
7             USA
8           Italy
9          Mexico
Name: Host, dtype: str

<div class="alert alert-success" role="alert"><p style="color:green">11c. How would you retrieve the value found in the 2nd row of the 2nd column?</p></div>

In [246]:
wcup.iloc[1,1]  #remember the 1st item of a list or series in Python is number 0. Thus, the second item is number 1.

'France'

12. We can us **.loc[..., ...]** to retrieve values, columns, or rows by their labels. For example, if we wanted to retrieve all info from the "Champion" column, we would simply run:

In [247]:
wcup.loc[:,"Champion"]

0    Argentina
1       France
2      Germany
3        Spain
4        Italy
5       Brazil
6       France
7       Brazil
8      Germany
9    Argentina
Name: Champion, dtype: str

12b. At the moment, rows are only indexed by numbers ("0", "1", "2" and so on). However, we can convert out "Year" column into an index:

In [248]:
wcup = wcup.set_index("Year")

Notice the slight change below (The lower placement of "Year" indicates it is now an index rather than a column):

In [249]:
wcup.head(3)

       Champion    Host
Year
2022  Argentina   Qatar
2018     France  Russia
2014    Germany  Brazil

12c. Now we can search the dataframe by our index ("Year") and by column name. For example:

In [250]:
wcup.loc[1994, "Champion"]

'Brazil'

**Note: for the code above, our index ("Year") has integers not strings. So running:*

```
wcup.loc["1994", "Champion"]
```

*will produce an error. Since 1994 is considered an integer here, we should leave the quotes out.*

12d. Like many things in Python, there are often multiple ways to accomplish the same goal. For example, we can also select particular columns by simply placing the names of a column within brackets (similar to indexing and slicing lists in Python).

In [251]:
# Use bracket notation to access the column 'Champion'
wcup['Champion']

Year
2022    Argentina
2018       France
2014      Germany
2010        Spain
2006        Italy
2002       Brazil
1998       France
1994       Brazil
1990      Germany
1986    Argentina
Name: Champion, dtype: str

In [252]:
# Access multiple columns
film_dialogue_df[["title", "character", "age"]]

                               title        character   age
0      The Bridges of Madison County            Betty 35.00
1      The Bridges of Madison County  Carolyn Johnson   NaN
2      The Bridges of Madison County          Eleanor   NaN
3      The Bridges of Madison County  Francesca Johns 46.00
4      The Bridges of Madison County            Madge 46.00
...                              ...              ...   ...
23042           Beauty and the Beast          Lumiere 56.00
23043           Beauty and the Beast          Maurice 71.00
23044           Beauty and the Beast  Monsieur D'Arqu 58.00
23045           Beauty and the Beast       Mrs. Potts 66.00
23046           Beauty and the Beast         Wardrobe 54.00

[23047 rows x 3 columns]

## V. Subset, Filter, and Sort a Dataframe

Frequently, when we are working with a dataset we may want to subset, filter, or sort the dataset before beginning your analysis.

Many of you may already be familiar with subsetting, filtering, and sorting datasets. But, just for review, this is what we mean by these terms:
+ **subset** - to subset a dataset is to create a smaller version of the dataset. For example, you may want to drop specific columns or rows to create a dataframe for your analysis

    <img src="https://pandas.pydata.org/docs/_images/03_subset_columns.svg" style="width:40%;">
    <img src="https://pandas.pydata.org/docs/_images/03_subset_rows.svg" style="width:40%;">
    
    + **filter** - filtering a dataframe is a specific type of subsetting. For example, you may want to drop all rows in a dataframe that contain missing values. Or keep only those rows that have a value that meets a particular condition.
+ **sort** - arrange the dataframe in a particular order. For example, you may want to sort a dataframe by a year or time column to arrange each row in chronological order. You may also sort a dataframe by multiple columns at once (i.e. sorting by year first and country second).
    <img src = "https://pythonexamples.org/images/python-pandas-dataframe-sort-by-index.svg" style = "width:40%">

Some examples of how you may want to subset, filter, or sort this lesson's dataframes: 

| Modification | World Cup dataset | Gapminder dataset | Film Dialogue dataset |
| :- | :- | :- | :- |
| **subset / filter** | create a df including only the 21st century men's World Cup champions | only review data from a set number of countries **or** for set range of years | keep only "title", "gender", and "proportion_of_dialogue" columns **or** only include data for film dialogue spoken by a character over 50 years old  |
| **sort** | Sort dataframe by year, but this time in ascending order | sort dataframe by life expectancy in 2007, in descending order | sort df by proportion of dialogue |

In [253]:
film_df.head(10)

,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,script_id
0,The Bridges of Madison County,1995,Betty,woman,311,0.05,35.00,142.00,280
1,The Bridges of Madison County,1995,Carolyn Johnson,woman,873,0.14,NaN,142.00,280
2,The Bridges of Madison County,1995,Eleanor,woman,138,0.02,NaN,142.00,280
3,The Bridges of Madison County,1995,Francesca Johns,woman,2251,0.35,46.00,142.00,280
4,The Bridges of Madison County,1995,Madge,woman,190,0.03,46.00,142.00,280
5,The Bridges of Madison County,1995,Michael Johnson,man,723,0.11,38.00,142.00,280
6,The Bridges of Madison County,1995,Robert Kincaid,man,1908,0.30,65.00,142.00,280
7,15 Minutes,2001,Bobby Korfin,man,328,0.04,NaN,37.00,623
8,15 Minutes,2001,Daphne Handlova,woman,409,0.04,28.00,37.00,623
9,15 Minutes,2001,Deputy Chief Fi,man,347,0.04,NaN,37.00,623

### Vb. Subsetting / Filtering

13. We can create data subsets by using the same slicing functions described in Part IV and saving them as new dataframes. For example:

In [254]:
wcup_last5 = wcup.iloc[:5,]
wcup_last5
# note, the head function can accomplish the exact same thing
#i.e. wcup_last5 = wcup.head()

       Champion          Host
Year
2022  Argentina         Qatar
2018     France        Russia
2014    Germany        Brazil
2010      Spain  South Africa
2006      Italy       Germany

<div class="alert alert-success" role="alert"><p style="color:green">13b. Let's take a look at the film_df again by using the .head() method.</p></div>

In [255]:
film_dialogue_df.head(2)

,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,script_id
0,The Bridges of Madison County,1995,Betty,woman,311,0.05,35.00,142.00,280
1,The Bridges of Madison County,1995,Carolyn Johnson,woman,873,0.14,NaN,142.00,280

13c. We can simplify things by only keeping the columns we need. 

Below are two different ways to subset by a dataframe by column name.

In [256]:
film_subset = film_dialogue_df[['release_year', 'title', 'proportion_of_dialogue']]
film_subset.head()

# notice: in the 1st line of code above, we not only selected 3 columns to keep but we also re-arranged their order!

   release_year                          title  proportion_of_dialogue
0          1995  The Bridges of Madison County                    0.05
1          1995  The Bridges of Madison County                    0.14
2          1995  The Bridges of Madison County                    0.02
3          1995  The Bridges of Madison County                    0.35
4          1995  The Bridges of Madison County                    0.03

In [257]:
#note: this does the same as above, only this time using the .loc[] method
film_subset = film_dialogue_df.loc[:,['release_year', 'title', 'proportion_of_dialogue']]
film_subset.head()

   release_year                          title  proportion_of_dialogue
0          1995  The Bridges of Madison County                    0.05
1          1995  The Bridges of Madison County                    0.14
2          1995  The Bridges of Madison County                    0.02
3          1995  The Bridges of Madison County                    0.35
4          1995  The Bridges of Madison County                    0.03

14. We can drop specific columns using the **.drop()** method for Pandas dataframes. For example, if we want to drop the "Host" column from our World Cup dataset, we could run the following:

In [258]:
print(wcup.shape)
print(wcup.head(2))
wcup2 = wcup.drop(columns = "Host")  #note: we need to add "wcup2 =" to save the changes to our original wcup dataframe as "wcup2"
                                    ##you could also just replace the original "wcup" by writing wcup = wcup.drop(...)
                                    ## however, often it is helpful to keep both the original, full dataframe and the smaller, subsetted one
print(wcup2.shape)
print(wcup2.head(2))

(10, 2)
       Champion    Host
Year
2022  Argentina   Qatar
2018     France  Russia
(10, 1)
       Champion
Year
2022  Argentina
2018     France

There are many different ways to drop specific columns or rows using .drop(). See the [Pandas 2 Constellate lesson](https://lab.constellate.org/monist-language/notebooks/tdm-notebooks-2023-04-19T18%3A59%3A16.317Z/pandas-2.ipynb) for some additional examples.

15. Commonly, for example, we may want to drop observations (rows) containing null data (warning: you should always consider what this removal does to the representative nature of your dataset!). We can use the **.dropna()** method. See some examples below:

In [259]:
print(film_dialogue_df.shape)
film_df_no_nas = film_dialogue_df.dropna()
print(film_df_no_nas.shape)

(23047, 9)
(15552, 9)

15b. Temporarily or permanently changing a dataframe: Most methods in Python just temporarily change a dataframe unless you assign the modified dataframe to a variable. For example:

```
film_dialogue_df.dropna()
```
just outputs a version of film_df with all NAs and null values removed, but does not save it to memory. If we wanted to replace the original "film_df" we can simply assign it the same name as follows:

```
film_dialogue_df = film_df.dropna()
```
Or we can save it under a new name as we did above:
```
film_df_no_nas = film_dialogue_df.dropna()
```

Finally, we can also use the "inplace" argument to do the same:

```
film_dialogue_df.dropna(inplace = True)
```

15c. You can also drop columns with missing values (this is much rarer than dropping rows with missing values):

In [260]:
film_df_dropcols = film_dialogue_df.dropna(axis = 1)    #for Pandas, rows are axis 0 and columns are axis 1
#film_df_dropcols = film_df.dropna(axis = "columns") # this does the same thing!

15d. More commonly, you may want to remove rows that are missing values for specific columns. For example, if you want to analyze the age of characters / actors given speaking roles in films, you would want to remove any characters (rows) for which we lack age data.

In [261]:
print(film_dialogue_df.shape)
film_df_age = film_dialogue_df.dropna(subset = "age")
film_df_age

(23047, 9)

,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,script_id
0,The Bridges of Madison County,1995,Betty,woman,311,0.05,35.00,142.00,280
3,The Bridges of Madison County,1995,Francesca Johns,woman,2251,0.35,46.00,142.00,280
4,The Bridges of Madison County,1995,Madge,woman,190,0.03,46.00,142.00,280
5,The Bridges of Madison County,1995,Michael Johnson,man,723,0.11,38.00,142.00,280
6,The Bridges of Madison County,1995,Robert Kincaid,man,1908,0.30,65.00,142.00,280
...,...,...,...,...,...,...,...,...,...
23042,Beauty and the Beast,1991,Lumiere,man,1063,0.10,56.00,452.00,9254
23043,Beauty and the Beast,1991,Maurice,man,1107,0.11,71.00,452.00,9254
23044,Beauty and the Beast,1991,Monsieur D'Arqu,man,114,0.01,58.00,452.00,9254
23045,Beauty and the Beast,1991,Mrs. Potts,woman,564,0.06,66.00,452.00,9254
23046,Beauty and the Beast,1991,Wardrobe,woman,121,0.01,54.00,452.00,9254

### Vc. Filtering a dataframe by a condition

16a. To filter a dataframe by a condition, first we need to define the filter itself:

In [262]:
movie_df['MPA'] == 'R'   #remember: "=" indicates an assignment and "==" indicates a comparison returning True if both sides are equal and False if not

0       False
1       False
2       False
3       False
4       False
        ...
2964     True
2965     True
2966     True
2967     True
2968     True
Name: MPA, Length: 2969, dtype: bool

16b. We can then assign this specific filter to a variable...

In [263]:
filter = (movie_df['MPA'] == 'R' )

16c. And use that filter to create a subset of our original dataset

In [264]:
df_R = movie_df.loc[filter]
df_R.head(3)

,Title,duration_minutes,MPA,Rating,votes,meta_score,genres,parent_genres,date,year,...,budget_estimated,budget_value,budget_currency,grossww_value,grossww_currency,directors,stars,awards_content,Languages,description
17,The King's Speech,118,R,8.00,720000,88.00,"['Period Drama', 'Political Drama', 'Biography...",drama,2010-12-25,2010.00,...,True,15000000,$,471155448,$,['Tom Hooper'],"['Colin Firth', 'Geoffrey Rush', 'Helena Bonha...","Won 4 Oscars, 109 wins & 206 nominations total",['English'],"The story of King George VI, his unexpected as..."
19,Shutter Island,138,R,8.20,1500000,63.00,"['Psychological Thriller', 'Suspense Mystery',...","thriller, mystery, drama",2010-02-19,2010.00,...,True,80000000,$,294978537,$,['Martin Scorsese'],"['Leonardo DiCaprio', 'Emily Mortimer', 'Mark ...","Awards, 11 wins & 66 nominations total","['English', 'German']",Two US marshals are sent to a mental instituti...
22,Jackass 3D,94,R,7.00,70000,56.00,"['Action', 'Comedy', 'Documentary']","act-ad, comedy, documentary",2010-10-15,2010.00,...,True,20000000,$,171685792,$,['Jeff Tremaine'],"['Johnny Knoxville', 'Steve-O', 'Bam Margera',...","Awards, 1 win & 4 nominations total",['English'],Johnny Knoxville and company return for the th...

16d. We can also filter by multiple conditions:

In [265]:
years_filt = (film_dialogue_df['release_year'] >= 1990) & (film_dialogue_df['release_year'] < 2000)
nineties_films = film_dialogue_df.loc[years_filt]     #note: you cannot begin a variable name with a number, thus 90s_films would raise an error
nineties_films.shape

(5838, 9)

We can also combine multiple filters to create an even smaller and more specific subset:

In [266]:
gross_filt = (film_dialogue_df['gross'] > 800)
nineties_blockbusters = film_dialogue_df.loc[years_filt & gross_filt]
nineties_blockbusters

,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,script_id
8066,Jurassic Park,1993,Dennis Nedry,man,584,0.05,38.00,844.00,2690
8067,Jurassic Park,1993,Donald Gennaro,man,509,0.04,46.00,844.00,2690
8068,Jurassic Park,1993,Dr. Alan Grant,man,2550,0.21,46.00,844.00,2690
8069,Jurassic Park,1993,Dr. Ellie Sattl,woman,1434,0.12,26.00,844.00,2690
8070,Jurassic Park,1993,Dr. Ian Malcolm,man,1317,0.11,41.00,844.00,2690
...,...,...,...,...,...,...,...,...,...
15330,Titanic,1997,Scotland Road S,man,154,0.01,NaN,1249.00,5136
15331,Titanic,1997,Spicer Lovejoy,man,287,0.02,56.00,1249.00,5136
15332,Titanic,1997,Thomas Andrews,man,559,0.04,48.00,1249.00,5136
15333,Titanic,1997,Tommy Ryan,man,166,0.01,25.00,1249.00,5136
15334,Titanic,1997,Woman,woman,116,0.01,52.00,1249.00,5136

<div class="alert alert-info" role="alert"><h3 style="color:blue;">Exercise for Part V. Subsets and Filters</h3>

<p style="color:blue;">17. Filter and subset the film_df to create a new dataset with only films from **a decade of your choosing**.</p>
</div>

In [267]:
years_filt = (film_dialogue_df['release_year'] >= 1970) & (film_dialogue_df['release_year'] < 1980)
seventies_films = film_dialogue_df.loc[years_filt] 
print(seventies_films.describe())  #we need a print() function to output this code b/c it is not the last line of code
seventies_films.head()  #as the last line of code in the cell, this will automatically output without a print() function

       release_year    words  proportion_of_dialogue    age   gross  script_id
count       1109.00  1109.00                 1109.00 897.00  340.00    1109.00
mean        1974.83   796.81                    0.09  41.50  424.25    4563.66
std            2.91  1179.07                    0.12  12.66  388.40    2470.47
min         1970.00   101.00                    0.00   8.00    6.00     666.00
25%         1972.00   181.00                    0.02  32.00  148.50    2328.00
50%         1975.00   355.00                    0.04  40.00  374.50    4489.00
75%         1977.00   882.00                    0.10  50.00  559.75    6958.00
max         1979.00 12487.00                    0.88  88.00 1798.00    8901.00

,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,script_id
196,American Graffiti,1973,Bob Falfa,man,248,0.03,31.00,565.00,666
197,American Graffiti,1973,Budda,woman,226,0.02,22.00,565.00,666
198,American Graffiti,1973,Carlos,man,131,0.01,18.00,565.00,666
199,American Graffiti,1973,Carol,woman,729,0.07,14.00,565.00,666
200,American Graffiti,1973,Curt,man,1240,0.13,26.00,565.00,666

<div class="alert alert-info" role="alert"><h3 style="color:blue;">Exercise for Part Vb: Subsetting</h3>

<p style="color:blue;">17b. Using the methods you learned above, what are some different ways you could go about subsetting and filtering the gapminder dataset so that it includes only data from Asia and only for the twenty-first century.</p>
</div>

Write some possible solutions here: 

* filter the "continent" column to save only rows where continent == "Asia"
* keep only the columns: "continent", "country", and the gdpPercap, lifeExp, and pop columns from 2002 and 2007.

<div class="alert alert-info" role="alert"><p style="color:blue;">17c. Implement one of your proposed solutions above to subset the gapminder dataset as described in 17b.</p></div>

In [268]:
gapminder_df.head()

       country continent  year  lifeExp       pop  gdpPercap
0  Afghanistan      Asia  1952    28.80   8425333     779.45
1  Afghanistan      Asia  1957    30.33   9240934     820.85
2  Afghanistan      Asia  1962    32.00  10267083     853.10
3  Afghanistan      Asia  1967    34.02  11537966     836.20
4  Afghanistan      Asia  1972    36.09  13079460     739.98

In [269]:
cont_filt = (gapminder_df['continent'] == "Asia")
year_filt = (gapminder_df['year'] >= 2000)
#year_filt = (gapminder_df['year'].between(2002, 2007))
gapminder_Asia_21C = gapminder_df[cont_filt & year_filt]

gapminder_Asia_21C

                 country continent  year  lifeExp        pop  gdpPercap
10           Afghanistan      Asia  2002    42.13   25268405     726.73
11           Afghanistan      Asia  2007    43.83   31889923     974.58
94               Bahrain      Asia  2002    74.80     656397   23403.56
95               Bahrain      Asia  2007    75.64     708573   29796.05
106           Bangladesh      Asia  2002    62.01  135656790    1136.39
...                  ...       ...   ...      ...        ...        ...
1655             Vietnam      Asia  2007    74.25   85262356    2441.58
1666  West Bank and Gaza      Asia  2002    72.37    3389578    4515.49
1667  West Bank and Gaza      Asia  2007    73.42    4018332    3025.35
1678         Yemen, Rep.      Asia  2002    60.31   18701257    2234.82
1679         Yemen, Rep.      Asia  2007    62.70   22211743    2280.77

[66 rows x 6 columns]

### Vd. Sorting a dataframe

18. We can sort a dataframe by the values in one column or in multiple columns using the **.sortvalues()** method.

In [270]:
film_dialogue_df.sort_values(by = ['release_year'])

,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,script_id
12343,The Cocoanuts,1929,Penelope,woman,534,0.06,24.00,NaN,4031
12339,The Cocoanuts,1929,Bob,man,668,0.08,42.00,NaN,4031
12340,The Cocoanuts,1929,Chico,man,915,0.11,42.00,NaN,4031
12341,The Cocoanuts,1929,Hammer,man,5577,0.65,39.00,NaN,4031
12344,The Cocoanuts,1929,Polly,woman,386,0.05,28.00,NaN,4031
...,...,...,...,...,...,...,...,...,...
16578,Youth,2015,Queen'S Emissar,man,240,0.03,41.00,2.00,5517
16577,Youth,2015,Miss Universe,woman,138,0.02,27.00,2.00,5517
15962,Carol,2015,Fred Haymes,man,300,0.03,57.00,NaN,5390
15963,Carol,2015,Harge Aird,man,383,0.04,50.00,NaN,5390
15964,Carol,2015,Jack Taft,man,216,0.02,NaN,NaN,5390

19. We can sort columns in descending order by adding the argument ```ascending = False``` (the default is "ascending = True").

In [271]:
film_dialogue_df.sort_values(by = ['release_year'], ascending = False)

,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,script_id
19960,The Boy Next Door,2015,Rhonda,woman,248,0.02,NaN,36.00,7704
21355,The Revenant,2015,Yellow Horse,man,216,0.04,NaN,147.00,8257
21354,The Revenant,2015,Runty Man,man,221,0.04,NaN,147.00,8257
21353,The Revenant,2015,Pig,man,381,0.07,NaN,147.00,8257
21352,The Revenant,2015,Murphy,man,137,0.03,43.00,147.00,8257
...,...,...,...,...,...,...,...,...,...
12343,The Cocoanuts,1929,Penelope,woman,534,0.06,24.00,NaN,4031
12341,The Cocoanuts,1929,Hammer,man,5577,0.65,39.00,NaN,4031
12340,The Cocoanuts,1929,Chico,man,915,0.11,42.00,NaN,4031
12342,The Cocoanuts,1929,Mrs. Potter,woman,492,0.06,47.00,NaN,4031
12339,The Cocoanuts,1929,Bob,man,668,0.08,42.00,NaN,4031

19b. When sorting by multiple columns, we need to specify which will be sorted in ascending rather than descending order using a list of the same length as the list of columns.

In [272]:
film_dialogue_df.sort_values(by = ['release_year', 'title', 'character'], ascending = [False, True, True])

,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,script_id
19997,American Ultra,2015,Adrian Yates,man,1833,0.22,37.00,14.00,7716
19998,American Ultra,2015,Krueger,man,386,0.05,62.00,14.00,7716
19999,American Ultra,2015,Laugher,man,105,0.01,44.00,14.00,7716
20000,American Ultra,2015,Mike Howell,man,1931,0.24,32.00,14.00,7716
20001,American Ultra,2015,Otis,man,226,0.03,51.00,14.00,7716
...,...,...,...,...,...,...,...,...,...
12340,The Cocoanuts,1929,Chico,man,915,0.11,42.00,NaN,4031
12341,The Cocoanuts,1929,Hammer,man,5577,0.65,39.00,NaN,4031
12342,The Cocoanuts,1929,Mrs. Potter,woman,492,0.06,47.00,NaN,4031
12343,The Cocoanuts,1929,Penelope,woman,534,0.06,24.00,NaN,4031
12344,The Cocoanuts,1929,Polly,woman,386,0.05,28.00,NaN,4031

<div class="alert alert-info" role="alert"><h3 style="color:blue;">Exercise for Part Vd. Sorting</h3>

<p style="color:blue;">20. Sort the gapminder dataframe by first the "continent" column and then the "country" column, but in descending (not ascending) order for each.</p></div>

In [273]:
gapminder_df.sort_values(by = ['continent', 'country'], ascending = [False, False])

          country continent  year  lifeExp       pop  gdpPercap
1092  New Zealand   Oceania  1952    69.39   1994794   10556.58
1093  New Zealand   Oceania  1957    70.26   2229407   12247.40
1094  New Zealand   Oceania  1962    71.24   2488550   13175.68
1095  New Zealand   Oceania  1967    71.52   2728150   14463.92
1096  New Zealand   Oceania  1972    71.89   2929100   16046.04
...           ...       ...   ...      ...       ...        ...
31        Algeria    Africa  1987    65.80  23254956    5681.36
32        Algeria    Africa  1992    67.74  26298373    5023.22
33        Algeria    Africa  1997    69.15  29072015    4797.30
34        Algeria    Africa  2002    70.99  31287142    5288.04
35        Algeria    Africa  2007    72.30  33333216    6223.37

[1704 rows x 6 columns]

<div class="alert alert-info" role="alert"><p style="color:blue;">20b. Sort the Gapminder dataframe in three ways to answer the following three questions:</p>
<ul>
<li style = "color:blue;">Which five countries had the largest population in 2007?</li>
<li style = "color:blue;">Which five countries had the highest GDP in 2007?</li>
<li style = "color:blue;">Which five countries had the highest life expectancy in 2007?</li>
</ul>
</div>

In [274]:
gapminder_Asia_21C[["continent", "country", "year", "pop"]].sort_values(by = "pop", ascending = False)

     continent    country  year         pop
299       Asia      China  2007  1318683096
298       Asia      China  2002  1280400000
707       Asia      India  2007  1110396331
706       Asia      India  2002  1034172547
719       Asia  Indonesia  2007   223547000
...        ...        ...   ...         ...
1006      Asia   Mongolia  2002     2674234
863       Asia     Kuwait  2007     2505559
862       Asia     Kuwait  2002     2111561
95        Asia    Bahrain  2007      708573
94        Asia    Bahrain  2002      656397

[66 rows x 4 columns]

In [275]:
year_filt = (gapminder_df['year'] == 2007)
gapminder_df.loc[year_filt, ["continent", "country", "gdpPercap"]].sort_values(by = "gdpPercap", ascending = False).head()

     continent        country  gdpPercap
1151    Europe         Norway   49357.19
863       Asia         Kuwait   47306.99
1367      Asia      Singapore   47143.18
1619  Americas  United States   42951.65
755     Europe        Ireland   40676.00

In [276]:
year_filt = (gapminder_df['year'] == 2007)
gapminder_df.loc[year_filt, ["continent", "country", "lifeExp"]].sort_values(by = "lifeExp", ascending = False).head()

     continent           country  lifeExp
803       Asia             Japan    82.60
671       Asia  Hong Kong, China    82.21
695     Europe           Iceland    81.76
1487    Europe       Switzerland    81.70
71     Oceania         Australia    81.23

## VI. Modify a Dataframe

There are many ways you can modify an existing dataframe.

21. You can change column names. First, let's review the names of our columns

In [277]:
wcup.columns

Index(['Champion', 'Host'], dtype='str')

In [278]:
wcup3 = wcup.rename(columns = {'Host': 'home_country'})
wcup3.head(2)

       Champion home_country
Year
2022  Argentina        Qatar
2018     France       Russia

22. Change values in the dataframe:

In [279]:
wcup.loc[2022, "Champion"] = "Messi!!"
wcup

       Champion          Host
Year
2022    Messi!!         Qatar
2018     France        Russia
2014    Germany        Brazil
2010      Spain  South Africa
2006      Italy       Germany
2002     Brazil   Korea/Japan
1998     France        France
1994     Brazil           USA
1990    Germany         Italy
1986  Argentina        Mexico

23. We can apply functions across an entire column using Pandas' **.apply()** method.

In [280]:
def make_uppercase(text):   #In Python you use "def" to define a function, give the function a name, and then you have the option of reading in additional arguments
    text_upper = text.upper()
    return(text_upper)

wcup['Host'].apply(make_uppercase)

Year
2022           QATAR
2018          RUSSIA
2014          BRAZIL
2010    SOUTH AFRICA
2006         GERMANY
2002     KOREA/JAPAN
1998          FRANCE
1994             USA
1990           ITALY
1986          MEXICO
Name: Host, dtype: str

23b. The code above only temporarily created a new "Host" column all in uppercase. Modify the code cell below so that there is a new column to store the uppercase values from the Host column.

In [281]:
wcup['Host'].apply(make_uppercase)

Year
2022           QATAR
2018          RUSSIA
2014          BRAZIL
2010    SOUTH AFRICA
2006         GERMANY
2002     KOREA/JAPAN
1998          FRANCE
1994             USA
1990           ITALY
1986          MEXICO
Name: Host, dtype: str

24. You can also create a new column using operands. For example, in the Gapminder dataset, we may want to calculate population change from 2002 to 2007 by subtracting the former from the latter. We can so by doing the following:

KeyError: 'pop_2007'

<div class="alert alert-info" role="alert"><h3 style="color:blue;">Exercises: Part VI Modifying a Dataframe</h3>

<p style="color:blue;">25. Following the code above, create a new column and then sort it to help you answer one of the following questions (you choose): </p>
<ul>
<li style="color:blue;">Which country's GDP improved the most between 1952 and 2007?</li>
<li style="color:blue;">Which country's life expectancy improved the most between 1952 and 2007?</li>
</ul>
</div>

In [283]:
gapminder_df.columns  #first we can view the columns we already have

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='str')

In [286]:
## try to do the GDP question on your own

<div class="alert alert-info" role="alert"><p style="color:blue;">26. Using a custom made function and the .apply() method create a new column in the film_df with each movie character's name capitalized.</p></div>

In [287]:
# let's first review our film_df
film_dialogue_df.head()

,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,script_id
0,The Bridges of Madison County,1995,Betty,woman,311,0.05,35.00,142.00,280
1,The Bridges of Madison County,1995,Carolyn Johnson,woman,873,0.14,NaN,142.00,280
2,The Bridges of Madison County,1995,Eleanor,woman,138,0.02,NaN,142.00,280
3,The Bridges of Madison County,1995,Francesca Johns,woman,2251,0.35,46.00,142.00,280
4,The Bridges of Madison County,1995,Madge,woman,190,0.03,46.00,142.00,280

In [288]:
#a simple function to read in a string (called "name") and return an upper-case version of that name
def make_uppercase(text):   #In Python you use "def" to define a function, give the function a name, and then you have the option of reading in additional arguments
    text_upper = text.upper()
    return(text_upper)   #note: we could also drop the line above and write return(name.upper()) here

In [297]:
#let's test our function
make_uppercase("I am angry!")

'I AM ANGRY!'

In [298]:
#... and apply it to our character column and save it to a new column "char_upper"
film_dialogue_df['char_upper'] = film_dialogue_df['character'].apply(make_uppercase)
film_dialogue_df.head()

,title,release_year,character,gender,words,proportion_of_dialogue,age,gross,script_id,char_upper
0,The Bridges of Madison County,1995,Betty,woman,311,0.05,35.00,142.00,280,BETTY
1,The Bridges of Madison County,1995,Carolyn Johnson,woman,873,0.14,NaN,142.00,280,CAROLYN JOHNSON
2,The Bridges of Madison County,1995,Eleanor,woman,138,0.02,NaN,142.00,280,ELEANOR
3,The Bridges of Madison County,1995,Francesca Johns,woman,2251,0.35,46.00,142.00,280,FRANCESCA JOHNS
4,The Bridges of Madison County,1995,Madge,woman,190,0.03,46.00,142.00,280,MADGE

## VII. Split-Apply-Combine

<img src = "https://www.oreilly.com/api/v2/epubs/9781783985128/files/graphics/5128OS_09_01.jpg" style="width:40%">

A commonly used data analysis strategy is **split-apply-combine**:
+ **split** the problem / data into manageable pieces
+ **apply** some calculations or analysis to the pieces
+ **combine** the parts back into a whole

For computational data science this means (from [Python Pandas documentation](https://pandas.pydata.org/docs/user_guide/groupby.html)):
```
    * Splitting the data into groups based on some criteria
    * Applying a function to each group independently
    * Combining the results into a data structure
```

Let's examine how this strategy may work for the datasets we have been working with. In our Gapminder dataset, for example, we may want to explore larger trends at the continent level. So we could:
+ **split** the overall dataset by continent, creating separate Africa, Asia, North America, South America, Oceania, and Europe datasets.
+ **apply** some calculations to each continental dataset; i.e. What is the average GDP and life expectancy of each continent in different years? Or what has been the average rate of change in these values from one five year interval to the next?
+ **combine** the data back together to compare changes in productivity (as measured by GDP) and health (as measured by life expectancy) by continent and over time.

Different applications apply this strategy in different ways. In Excel, you would use pivot tables, SQL the "group by" operator, and in R you may use the plyr package.

With Pandas, we can use the **.groupby()**, **.agg()**, and **.apply()** functions to do this. 
+ **.groupby()** - *splits* a dataset into separate groups
+ **.agg()** - used to calculate multiple statistics per group in one calculation
+ **.apply()** - applies a function across an entire column (or row) in a Pandas dataframe

Let's re-examine the contents of our Gapminder dataframe. 

27. Use the .head() method to output its first five rows and use the .columns method to output summary information about this dataframe.

In [299]:
gapminder_df.head()

       country continent  year  lifeExp       pop  gdpPercap
0  Afghanistan      Asia  1952    28.80   8425333     779.45
1  Afghanistan      Asia  1957    30.33   9240934     820.85
2  Afghanistan      Asia  1962    32.00  10267083     853.10
3  Afghanistan      Asia  1967    34.02  11537966     836.20
4  Afghanistan      Asia  1972    36.09  13079460     739.98

In [300]:
gapminder_df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='str')

### VIIb: Groupby()

*This first few cells of this section are adapted from Constellate's [3rd Pandas tutorial](https://lab.constellate.org/practical-diabetes-methods/notebooks/tdm-notebooks-2023-04-20T12%3A35%3A07.477Z/pandas-3.ipynb).*

28. Groupby is a powerful function built into Pandas that you can use to summarize your data. Groupby splits the data into different groups on a variable of your choice. 

To learn more about using Pandas **.groupby()** to split-apply-combine data, see the [documentation here](https://pandas.pydata.org/docs/user_guide/groupby.html).

In [301]:
# Group the data by continent
gapminder_df.groupby('continent')

29. The groupby() method returns a GroupBy object which describes how the rows of the original dataset have been split by the selected variable. You can actually see how the rows of the original dataframe have been grouped using the ```groups``` attribute after applying ```groupby().```

In [302]:
# See how the rows have been grouped
gapminder_df.groupby('continent').groups
#Note: this dataset had already been sorted by continent.

{'Africa': [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, ...], 'Americas': [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 432, 433, 434, 435, ...], 'Asia': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, ...], 'Europe': [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 516, 517, 518, 519, ...], 'Oceania': [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103]}

30. Of course, we don't just stop at grouping data. Grouping data is just a step towards data query. After we apply the .groupby() method, we can actually use different Pandas methods to query the data. For example, how do we get the number of documents in each docType by publicationYear?

In [303]:
# Create a series storing the number of documents in each doc type by year
gapminder_df.groupby('continent').size()

continent
Africa      624
Americas    300
Asia        396
Europe      360
Oceania      24
dtype: int64

We can then use the **.agg()** (aggregate) method to choose what functions we will **apply** to each group to allow us to **combine** the data back together.

The general formula for applying functions using the aggregate (.agg()) method:

```
df_name.groupby('col_name').agg({dict assigning a function to each column we want to aggregate})

```
where the format for each dictionary is as follows:
```
{'name_of_col1_to_keep': 'function_to_apply_to_this_col', 'name_of_col2_to_keep': 'function_to_apply_to_this_col'}
```

Some commonly used functions with groupby ([click here](https://pandas.pydata.org/pandas-docs/stable/reference/groupby.html#computations-descriptive-stats) for a full list):
+ .count(), .mean(), .min(), .max(), .sum()

31. With this in mind, examine the following line of code. What do you guess it does? Run it and see if you were correct?

In [305]:
year_filt = (gapminder_df['year'] == 2002)
gapminder_df.loc[year_filt, :].groupby('continent').agg({'lifeExp':'mean'})

           lifeExp
continent
Africa       53.33
Americas     72.42
Asia         69.23
Europe       76.70
Oceania      79.74

32. We can use the .agg() method to apply multiple functions to multiple columns:

In [ ]:
# cont_pop_chg = gapminder_df.groupby('continent').agg({'pop_2002':'sum', 'pop_2007': 'sum'})
# cont_pop_chg

             pop_2002    pop_2007
continent
Africa      833723916   929539692
Americas    849772762   898871184
Asia       3601802203  3811953827
Europe      578223869   586098529
Oceania      23454829    24549947

33. We can then use these two columns in the continental dataset to calculate percent population change between 2002 and 2007:

In [ ]:
# cont_pop_chg['pct_chg_02-07'] = 100 * (cont_pop_chg['pop_2007'] - cont_pop_chg['pop_2002']) / cont_pop_chg['pop_2002']
# cont_pop_chg

             pop_2002    pop_2007  pct_chg_02-07
continent
Africa      833723916   929539692      11.492507
Americas    849772762   898871184       5.777830
Asia       3601802203  3811953827       5.834624
Europe      578223869   586098529       1.361870
Oceania      23454829    24549947       4.669051

<div class="alert alert-info" role="alert"><h3 style="color:blue;">Exercises Part VII: Split-Apply-Combine</h3></div>

<div class="alert alert-info" role="alert"><p style="color:blue;">34. Using what you learned above, group the gapminder_df by continent again, but this time calculating the average change in life expectancy for each continent between 1952 and 2007.</p></div>

In [ ]:
# lifeexp_chg = gapminder_df.groupby('continent').agg({'lifeExp_1952':'mean', 'lifeExp_2007': 'mean'})
##Note: if you really wanted to calculate a precise statistic recording the change in life expectancy for each person on each continent, 
    ## you would probably want to weigh the average for each country by that country's population before averaging for across the continent
# lifeexp_chg['lifeExp_chg'] = (lifeexp_chg['lifeExp_2007'] - lifeexp_chg['lifeExp_1952']) 
# lifeexp_chg

           lifeExp_1952  lifeExp_2007  lifeExp_chg
continent
Africa        39.135500     54.806038    15.670538
Americas      53.279840     73.608120    20.328280
Asia          46.314394     70.728485    24.414091
Europe        64.408500     77.648600    13.240100
Oceania       69.255000     80.719500    11.464500